<template>
  <div class="newsletter" :class="{ show: active }">
    <div class="newsletter__box" :class="{ show: active }">
      <div class="newsletter__box--item">
        <h2 class="newsletter__title">NEWSLETTER</h2>
        <div class="box-close" @click="$emit('close-newsletter-box')">X</div>
        <p>
          Join our mailing list to receive updates on new arrivals and special
          offers.
        </p>
        <form action="#" class="newsletter__form">
          <input type="email" name="email" class="newsletter__form--input" />
          <input type="submit" class="newsletter__form--button" />
        </form>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  props: ["active"],
};
</script>

<style scoped>
.newsletter {
  position: absolute;
  display: none;
}

.newsletter.show {
  display: block;
  z-index: 1;
}
.newsletter__box {
  width: 100vw;
  height: 100vh;
  background-color: rgba(114, 113, 113, 0.397);
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  margin: 0 auto;
  transition: left 1s;
  z-index: 9999;
}
.newsletter__box--item {
  max-width: 900px;
  margin: 0 auto;
  background-color: white;
  -webkit-animation: scale-up-center 0.5s cubic-bezier(0.39, 0.575, 0.565, 1)
    both;
  animation: scale-up-center 0.5s cubic-bezier(0.39, 0.575, 0.565, 1) both;
}
.newsletter__title {
  margin: 40vh 0 0 0;
}
.newsletter__form {
  display: flex;
  flex-direction: column;
  width: 90%;
  margin: 0 auto;
}
.box-close {
  font-size: 1.5rem;
  padding: 5px;
  border-radius: 5px;
  right: 10px;
  color: white;
  width: 15px;
  float: right;
  cursor: pointer;
  background-color: black;
}
.box-close:hover {
  background-color: gray;
  color: #000;
}
/* ----------------------------------------------
 * Generated by Animista on 2021-11-15 15:39:9
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

@-webkit-keyframes scale-up-center {
  0% {
    -webkit-transform: scale(0);
    transform: scale(0);
  }
  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }
}
@keyframes scale-up-center {
  0% {
    -webkit-transform: scale(0);
    transform: scale(0);
  }
  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }
}
</style>
