<template>
  <div class="information" :class="{ show: active }">
    <div class="information__box" :class="{ show: active }">
      <div class="information__box--item">
        <h2 class="information__title">Rezerwacja</h2>
        <div class="box-close" @click="$emit('close-information-box')">X</div>

        <p>Zarezerwowane miejsca:</p>

        <div v-for="seat in seats" :key="seat.id" :seat="seat">
          <div class="seat-cords" v-if="seat.counter % 2">
            Rząd {{ seat.cords.rzad }}, Miejsce {{ seat.cords.miejsce }}
          </div>
        </div>
        <router-link
          v-if="seats.length > 0 && seats.some((seat) => seat.counter % 2)"
          class="btn-payment"
          :class="{ active: $route.name === 'Form' }"
          to="/form"
          >Przejdź do płatności</router-link
        >
      </div>
    </div>
  </div>
</template>

<script>
export default {
  props: ["active"],
  computed: {
    seats() {
      return this.$store.getters.reservationItem;
    },
  },
};
</script>

<style scoped>
.information {
  display: none;
}
.seat-cords {
  display: flex;
  justify-content: center;
  font-size: 18px;
  margin: 10px 0;
}
.btn-payment {
  display: flex;
  background-color: orange;
  width: 150px;
  margin: 0 auto;
  height: 50px;
  text-decoration: none;
  color: white;
  align-items: center;
  justify-content: center;
  font-weight: bold;
  border-radius: 10px;
}

.information.show {
  display: block;
  z-index: 100;
  position: fixed;
  width: 100vw;
  height: 100vh;
  background-color: rgba(114, 113, 113, 0.397);
  top: 0;
  left: 0;
  right: 0;
}
.information__box {
  max-width: 900px;
  margin: 0 auto;
  -webkit-animation: scale-up-center 0.5s cubic-bezier(0.39, 0.575, 0.565, 1)
    both;
  animation: scale-up-center 0.5s cubic-bezier(0.39, 0.575, 0.565, 1) both;
}
.information__box--item {
  margin: 32px;
  height: 100%;
  background-color: white;
  z-index: 100;
  padding-bottom: 20px;
}
.information__title {
  margin: 30vh 0 0 0;
  padding-top: 32px;
  display: flex;
  justify-content: center;
  font-size: 30px;
  font-weight: 400;
}
.information__form {
  display: flex;
  flex-direction: column;
  width: 90%;
  margin: 0 auto;
}
.box-close {
  position: absolute;
  font-size: 1.5rem;
  padding: 5px;
  border-radius: 5px;
  right: 75px;
  top: 32px;
  color: white;
  width: 15px;
  float: right;
  cursor: pointer;
  background-color: black;
}
.box-close:hover {
  background-color: gray;
  color: #000;
}
p {
  display: flex;
  justify-content: center;
  font-size: 15px;
}
.information__form--input {
  padding: 8px;
  margin-bottom: 20px;
}
.information__form--button {
  padding: 12px 24px;
  width: 122px;
  height: 46px;
  margin: 0 auto;
  background-color: rgb(250, 55, 20);
  border-radius: 5px;
  border: none;
  color: white;
  cursor: pointer;
}
.information__form--button:hover {
  background-color: gray;
  color: black;
}
@media screen and (max-width: 650px) {
  .information__title {
    font-size: 20px;
  }
  .box-close {
    font-size: 20px;
    top: 20px;
    right: 50px;
  }
  p {
    text-align: center;
  }
  .btn-payment {
    text-align: center;
  }
}
/* ----------------------------------------------
 * Generated by Animista on 2021-11-15 15:39:9
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

@-webkit-keyframes scale-up-center {
  0% {
    -webkit-transform: scale(0);
    transform: scale(0);
  }
  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }
}
@keyframes scale-up-center {
  0% {
    -webkit-transform: scale(0);
    transform: scale(0);
  }
  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }
}
</style>
